### ISSUE TITLE
`craco test` fails

### ISSUE THREAD

**Issue by nirvdrum** [DocSpring/craco-antd#24]
I've updated my package.json as shown in the test app, so I have:

```
"scripts": {
  "test": "craco test"
}
```
With this change, my test suite no longer runs. I went and checked out the craco-antd test app and I can't get `yarn test` to work there either. It looks like the less compiler isn't being invoked when it should :

```
 FAIL  src/App.test.tsx
  ● Test suite failed to run

    /home/nirvdrum/dev/workspaces/craco-antd/test-app/node_modules/antd/es/button/style/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import '../../style/index.less';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      10 | };
      11 | 
    > 12 | class App extends Component<any, State> {
         | ^
      13 |   state: State;
      14 | 
      15 |   constructor(props: any) {

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
      at Object.<anonymous> (src/App.tsx:12:1)
```

**Comment by filipjnc** [comment]
The fix is [here](https://github.com/facebook/jest/issues/7957#issuecomment-533947800).

**Comment by nirvdrum** [comment]
Thanks for letting me know there's a solution available.

**Comment by alistairjcbrown** [comment]
Has this issue been fixed now that PR #31 has landed and been released?

**Comment by nirvdrum** [comment]
I'll try it out shortly. I had been holding off on upgrading for #42. I wasn't sure if the releases on NPM were legitimate or a hacked account.
