### ISSUE TITLE
craco test

### ISSUE THREAD

**Issue by miguelc1221** [DocSpring/craco-antd#48]
Not sure if it's related to this plugin but running craco test is not allowing my tests to pass. I am using create-react-app with typescript. I get the following error

```
node_modules/antd/lib/style/index.less:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){@import './themes/index';
                                                                                             ^

    SyntaxError: Invalid or unexpected token

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/antd/lib/row/style/index.js:3:1)
```

This is what my config looks like 

```
module.exports = {
  plugins: [
    {
      plugin: CracoAntDesignPlugin,
      options: {
        customizeTheme: antOverrides,
      },
    },
  ],
  jest: {
    configure: {
      transformIgnorePatterns: ['node_modules[/\\\\](?!@amcharts[/\\\\]amcharts4)'],
    },
  },
};
```

```
    "@craco/craco": "^5.7.0",
    "antd": "^4.6.4",
    "craco-antd": "^1.18.1",
```

**Comment by gynekolog** [comment]
Did you try [instructions from Antd documentation](https://ant.design/docs/react/use-with-create-react-app#Test-with-Jest)?

`package.json`:
```
"jest": {
  "transformIgnorePatterns": [
    "/node_modules/(?!antd|@ant-design|rc-.+?|@babel/runtime).+(js|jsx)$"
  ]
}
```
